version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:7.0.12-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes: 
      - ./db/redis:/data