when:
  event: push
  path:
    include: ["docs/**", "mkdocs.yml"]
  branch: main
steps:
  build:
    image: squidfunk/mkdocs-material
    commands:
      - mkdocs build --site-dir build
      - cd build
      - git clone https://codeberg.org/cryap/pages.git
      - cp -r pages/.git .
      - rm -rf pages
      - cp docs/_redirects build/
      - git remote remove origin
  push:
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: main
      path: build
      commit: true
      remote: git@codeberg.org:cryap/pages.git
      commit_message: deploy from main
      author_name: Deploy
      force: true
      ssh_key:
        from_secret: pages_ssh_key
runs_on: [success, failure]
